### ISSUE TITLE
Playing an mp4 does not open a window

### ISSUE THREAD

**Issue by Poikilos** [osom8979/avplayer#1]
- Python 3.10.12
- avplayer git [aad9dd4](https://github.com/osom8979/avplayer/commit/aad9dd4bc344d845892a1de55ed6bb394a3e4b0f)
- new venv with requirements.main.txt installed

With audio (same result if using `python main.py video.mp4`):
```
python -m avplayer video.mp4 
Skip the flushing packet, shutdown count: 1/10
Skip the flushing packet, shutdown count: 2/10
Skip the flushing packet, shutdown count: 3/10
Skip the flushing packet, shutdown count: 4/10
Skip the flushing packet, shutdown count: 5/10
Skip the flushing packet, shutdown count: 6/10
Skip the flushing packet, shutdown count: 7/10
Skip the flushing packet, shutdown count: 8/10
Skip the flushing packet, shutdown count: 9/10
Skip the flushing packet, shutdown count: 10/10
End of file: The flush count has reached its maximum
```

- No window appears.
- Using an mp4 file with no audio, the result is the same.
- [ ] If using it this way is supposed to run a backend, maybe provide console output saying something like "server mode (no GUI mode specified for --app-type)"

I'm doing what the readme says, but I'm not sure what the program is supposed to do or how to see the video. Maybe update the readme if I'm doing something wrong.

Ok maybe add this to examples in readme and help:
```
# GUI requires: pip install -e "avplayer[pillow]"
python -m avplayer -c -d -vv video.mp4 --app-type=aiotk
```
comment above is suggested to be shown to user since otherwise it gives
```
ModuleNotFoundError: No module named 'PIL'

```

After installing Pillow, I still get
```
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
```

A solution is discussed here: https://stackoverflow.com/a/50673800/4541104

**Comment by osom8979** [comment]
I have confirmed. Thank you.
